# Generated by Django 3.0.8 on 2020-07-29 07:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200729_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for the author', primary_key=True, serialize=False),
        ),
    ]
